### ISSUE TITLE
On custom rom like MIUI, VIVO, OPPO have you test this code for continuous location tracking

### ISSUE THREAD

**Issue by amitdoiphode11** [BlackBlind567/Location_Updates-Background_Foreground#1]
Hi, @BlackBlind567 thank you for this project. But I am facing an issue on other than stock android os device. Have you test location on other devices? 
**Problem:**
If App is killed then in service **onTaskRemoved** called android notification is still there but we don't have to get locations after the app is killed.

Already created an [issue](https://github.com/codepath/android_guides/issues/351#issue-389175394).

**Comment by BlackBlind567** [comment]
first you want to check notification after app killed so reduces the time of getting location . And second one is I checked in MI, VIVO and NOKIA. Something else??
